
// This file is automatically generated. Do not edit it directly.
import { supabase } from "./client";
import type { Database } from "./database.types";
import type { PostgrestQueryBuilder } from '@supabase/postgrest-js';

// Type-safe DB helper that allows accessing tables without type errors
export const db = {
  // Direct access to tables with proper types
  from: <T extends keyof Database['public']['Tables']>(
    table: T
  ) => {
    return supabase.from(table) as PostgrestQueryBuilder<
      Database['public']['Tables'][T]['Row'],
      Database['public']['Tables'][T]['Row'],
      unknown
    >;
  },
  
  // Helper method for casting response data to a specific type
  cast: <T>(data: any): T => {
    return data as unknown as T;
  }
};

// Type assertion helper for when TypeScript has issues with table definitions
export function asType<T>(data: any): T {
  return data as unknown as T;
}
